#!/usr/bin/env node
/**
 * Generate docs/assurance-report.md: exactly what these standards can prevent from being overstated,
 * and what still requires expert judgement.
 *
 * WHY THIS IS GENERATED. The source prompt's closing requirement is a report on that boundary, and a
 * hand-written one would be a claim about the tooling maintained separately from the tooling. It
 * would drift, and it would drift in the flattering direction — nobody remembers to downgrade a
 * capability claim. So the report is derived from the same JSON the validator consumes: the
 * `assurance` field partitions the rules, each rule's `$assuranceNote` supplies its own caveat
 * verbatim, and the coverage figures are computed rather than recalled.
 *
 * Usage:
 *   node scripts/assurance.mjs           write docs/assurance-report.md
 *   node scripts/assurance.mjs --check   exit 1 if the committed report is stale
 *   node scripts/assurance.mjs --stdout  print instead of writing
 */

import { readFile, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { loadCatalog, coverage } from "./catalog.mjs";
import { isInvariant } from "./compliance.mjs";
import { EVALUATED_RULES } from "./evaluated.mjs";

const HOME = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = path.join(HOME, "docs/assurance-report.md");

const catalog = await loadCatalog(path.join(HOME, "rules"));

const standardPaths = new Map();
let totalStandards = null;
try {
  const inv = JSON.parse(await readFile(path.join(HOME, "artifacts/standards-source-inventory.json"), "utf8"));
  totalStandards = inv.expectedCount ?? inv.standards?.length ?? null;
  for (const s of inv.standards ?? []) standardPaths.set(s.number, s.implementedBy);
} catch {
  // Leave the links out rather than inventing paths.
}

const evaluated = new Set(EVALUATED_RULES);
const rules = [...catalog.rules.values()].sort((a, b) => a.id.localeCompare(b.id));
const cover = coverage(catalog, { evaluated: EVALUATED_RULES, totalStandards });

const link = (rule) => {
  const doc = standardPaths.get(rule.standard);
  return doc ? `[Standard ${rule.standard}](../${doc})` : `Standard ${rule.standard}`;
};

const section = (title, blurb, subset) => {
  const lines = [`## ${title}`, "", blurb, ""];
  if (subset.length === 0) {
    lines.push("_No rules in this tier._", "");
    return lines;
  }
  for (const rule of subset) {
    lines.push(`### \`${rule.id}\``);
    lines.push("");
    lines.push(
      `${link(rule)} · ${rule.level}${isInvariant(rule) ? " (invariant — no exception reaches it)" : ""} · ` +
        `${rule.severity} · ${rule.validationType}` +
        (evaluated.has(rule.id) ? "" : " · **not evaluated by any detector**"),
    );
    lines.push("");
    lines.push(rule.description);
    lines.push("");
    lines.push(`**What the check does not establish.** ${rule["$assuranceNote"]}`);
    lines.push("");
  }
  return lines;
};

const full = rules.filter((r) => r.assurance === "full");
const partial = rules.filter((r) => r.assurance === "partial");
const none = rules.filter((r) => r.assurance === "none");

const invariants = rules.filter(isInvariant);
const unevaluated = rules.filter((r) => !evaluated.has(r.id));

const out = [
  "# Assurance report",
  "",
  "<!-- GENERATED by scripts/assurance.mjs from rules/*.json. Do not edit by hand: the point of",
  "     generating it is that the claim about what the tooling establishes cannot drift away from",
  "     the tooling. Run `npm run assurance` after any catalog change. -->",
  "",
  "This is the answer to the closing requirement of the source prompt: what these standards can",
  "prevent from being overstated, and what still requires expert judgement. It is generated from the",
  "rule catalog, so it cannot claim coverage the rules do not declare.",
  "",
  "## Coverage",
  "",
  "| Figure | Value |",
  "| --- | --- |",
  `| Rules in the catalog | ${cover.cataloguedRules} |`,
  `| Rules with a detector | ${cover.evaluatedRules} |`,
  `| Rules with no detector (report not-evaluated, never passed) | ${unevaluated.length} |`,
  `| Prohibitions (\`forbidden\` + \`nonExemptible\`) | ${invariants.length} |`,
  `| Standards carrying at least one rule | ${cover.standardsWithRules} of ${cover.standards ?? "?"} |`,
  `| Standards fully machine-represented | ${cover.fullyMachineRepresentedStandards} of ${cover.standards ?? "?"} |`,
  "",
  "A standard counts as fully machine-represented only when every rule it contributes is evaluated by",
  "a detector **and** carries assurance above `none`. The strict definition is deliberate: a looser one",
  "would let the number rise without the tooling improving.",
  "",
  "These figures are framework maturity. They are never combined with a compliance score, because a",
  "coverage improvement must not be able to look like a compliance improvement.",
  "",
  ...section(
    "Prevented outright",
    "Assurance `full`. These checks establish their property completely over what the repository " +
      "contains. A violation cannot ship past a run of `math-standards validate`.",
    full,
  ),
  ...section(
    "Prevented over what is declared",
    "Assurance `partial`. These checks are exact over the ledger, the policy, and the files the " +
      "project wrote down — and blind to everything outside them. The recurring limit, stated once " +
      "here and again per rule below: the detector sees the declared graph, not the mathematics. An " +
      "undeclared dependency, an unregistered claim, or a dishonest ledger entry is invisible.",
    partial,
  ),
  ...section(
    "Requires expert judgement",
    "Assurance `none`. Automation contributes vocabulary and an audit trail here, not verdicts. Each " +
      "of these rules exists so that a reviewer has a named thing to check, a claimant has a named " +
      "thing to attest to, and the coverage figure counts the gap instead of hiding it. They report " +
      "`not-evaluated` in every automated run — never `passed`.",
    none,
  ),
  "## The short version",
  "",
  "**What this system reliably prevents.** A claim status outside the fifteen-token vocabulary. A",
  "status that disagrees with its own recorded history. A claim at proved rank whose declared",
  "dependencies include a conjecture. A dependency cycle — the target theorem assumed in its own",
  "proof, however many lemmas the route passes through. A claim at proved rank with an open",
  "obligation. A claim whose only declared evidence is computational. A universal statement supported",
  "by a bounded check. A `MACHINE_CHECKED_PROOF` citing a file that contains `sorry`, or citing",
  "nothing, or citing a file that does not exist. An undisclosed axiom. An open-problem record with",
  "an unanswered section. Evidence pointing at a file that is not there. A source prompt edited after",
  "the fact. And — the rule the rest protect — a rule nothing evaluated being reported as passing.",
  "",
  "**What still requires a mathematician.** Whether a proof is correct. Whether an assumption was",
  "used and never declared, which is what makes it hidden. Whether a symbolic step's validity",
  "condition holds. Whether a stated domain is the domain the proof covers. Whether a citation says",
  "what it is cited for. Whether a counterexample was found and suppressed, or a failed run deleted —",
  "both leave no artifact, by construction. Whether a reformulation is progress or the same",
  "difficulty renamed. Whether a formal statement is the theorem the paper claims. And whether any",
  "particular change to a standard was made because the standard was wrong or because it was in the",
  "way.",
  "",
  "The second list is not a backlog. Several of its entries are unmechanisable in principle, and",
  "saying so is a requirement of the standards themselves: a tool that overstated its own coverage",
  "would be committing the error it exists to prevent.",
  "",
].join("\n");

if (process.argv.includes("--stdout")) {
  process.stdout.write(out);
  process.exit(0);
}

if (process.argv.includes("--check")) {
  const current = existsSync(OUTPUT) ? await readFile(OUTPUT, "utf8") : "";
  if (current.replace(/\r/g, "") === out.replace(/\r/g, "")) {
    process.stdout.write("docs/assurance-report.md is current.\n");
    process.exit(0);
  }
  process.stdout.write("docs/assurance-report.md is stale. Run `npm run assurance`.\n");
  process.exit(1);
}

await writeFile(OUTPUT, out, "utf8");
process.stdout.write(
  `Wrote docs/assurance-report.md — ${cover.cataloguedRules} rule(s): ` +
    `${full.length} full, ${partial.length} partial, ${none.length} expert-judgement.\n`,
);
